import Footer from "./Footer";
import Header from "./Header";
import Head from "next/head";

const Layout = ({ children }) => {
	return (
		<>
			<Head>
				<title>Chattam</title>
				<meta
					name="description"
					content="Generated by TAM (Tarique Ali Mirza <tarique1988@gmail.com>)"
				/>
			</Head>
			<div className="flex flex-col items-center justify-between min-h-screen">
				<Header />
				{children}
				<Footer />
			</div>
		</>
	);
};

export default Layout;
